apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z0iwoa0gt-nodejs
  janus-idp.io/tekton: z0iwoa0gt-nodejs
  backstage.io/kubernetes-id: z0iwoa0gt-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z0iwoa0gt-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
